#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
picom -b --config ~/.config/picom/picom.conf &

bspc monitor HDMI-0 -d I II III IV V VI 

bspc config border_width         2
bspc config focused_border_color "#5E81AC"

bspc config window_gap		 6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on
bspc rule -a firefox -o desktop='^2' follow=on
bspc rule -a Pcmanfm -o desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
